# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/Vivado/KRIA_KV260_DMA/KRIA_KV260_DMA.srcs/sources_1/bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_dma_0_0/KRIA_KV260_DMA_axi_dma_0_0.xci
# IP: The module: 'KRIA_KV260_DMA_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Vivado/KRIA_KV260_DMA/KRIA_KV260_DMA.gen/sources_1/bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_dma_0_0/KRIA_KV260_DMA_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'KRIA_KV260_DMA_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Vivado/KRIA_KV260_DMA/KRIA_KV260_DMA.gen/sources_1/bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_dma_0_0/KRIA_KV260_DMA_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'KRIA_KV260_DMA_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Vivado/KRIA_KV260_DMA/KRIA_KV260_DMA.gen/sources_1/bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_dma_0_0/KRIA_KV260_DMA_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'KRIA_KV260_DMA_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Projects/Vivado/KRIA_KV260_DMA/KRIA_KV260_DMA.srcs/sources_1/bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_dma_0_0/KRIA_KV260_DMA_axi_dma_0_0.xci
# IP: The module: 'KRIA_KV260_DMA_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Vivado/KRIA_KV260_DMA/KRIA_KV260_DMA.gen/sources_1/bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_dma_0_0/KRIA_KV260_DMA_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'KRIA_KV260_DMA_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Vivado/KRIA_KV260_DMA/KRIA_KV260_DMA.gen/sources_1/bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_dma_0_0/KRIA_KV260_DMA_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'KRIA_KV260_DMA_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Vivado/KRIA_KV260_DMA/KRIA_KV260_DMA.gen/sources_1/bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_dma_0_0/KRIA_KV260_DMA_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'KRIA_KV260_DMA_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
