# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/KRIA_KV260_DMA/KRIA_KV260_DMA.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA || ORIG_REF_NAME==KRIA_KV260_DMA} -quiet] -quiet

# IP: bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_zynq_ultra_ps_e_0_0/KRIA_KV260_DMA_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==KRIA_KV260_DMA_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_dma_0_0/KRIA_KV260_DMA_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA_axi_dma_0_0 || ORIG_REF_NAME==KRIA_KV260_DMA_axi_dma_0_0} -quiet] -quiet

# IP: bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_auto_ds_0/KRIA_KV260_DMA_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA_auto_ds_0 || ORIG_REF_NAME==KRIA_KV260_DMA_auto_ds_0} -quiet] -quiet

# IP: bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_auto_pc_0/KRIA_KV260_DMA_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA_auto_pc_0 || ORIG_REF_NAME==KRIA_KV260_DMA_auto_pc_0} -quiet] -quiet

# IP: bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_ps8_0_axi_periph_0/KRIA_KV260_DMA_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA_ps8_0_axi_periph_0 || ORIG_REF_NAME==KRIA_KV260_DMA_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_rst_ps8_0_99M_0/KRIA_KV260_DMA_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA_rst_ps8_0_99M_0 || ORIG_REF_NAME==KRIA_KV260_DMA_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_smc_1/KRIA_KV260_DMA_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA_axi_smc_1 || ORIG_REF_NAME==KRIA_KV260_DMA_axi_smc_1} -quiet] -quiet

# IP: bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axi_smc_1_0/KRIA_KV260_DMA_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA_axi_smc_1_0 || ORIG_REF_NAME==KRIA_KV260_DMA_axi_smc_1_0} -quiet] -quiet

# IP: bd/KRIA_KV260_DMA/ip/KRIA_KV260_DMA_axis_data_fifo_0_0/KRIA_KV260_DMA_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KRIA_KV260_DMA_axis_data_fifo_0_0 || ORIG_REF_NAME==KRIA_KV260_DMA_axis_data_fifo_0_0} -quiet] -quiet

# XDC: d:/KRIA/KRIA_KV260_DMA/KRIA_KV260_DMA.gen/sources_1/bd/KRIA_KV260_DMA/KRIA_KV260_DMA_ooc.xdc
